version: "3.8"

services:
    app:
        image: nginx:latest
        depends_on:
            - database
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80" # host:container

    database:
        image: mysql:8.0.40
        environment:
            MYSQL_USER: "ddn"
            MYSQL_DATABASE: "db_ta"
            MYSQL_PASSWORD: "REIYANn020711SISTEM22!"
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        ports:
            - "8306:3306" # host:container
        volumes:
            - database:/var/lib/mysql

volumes:
    database:
